# Generated by Django 4.2.1 on 2023-06-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
