# Generated by Django 4.2.1 on 2023-06-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
