# Generated by Django 4.2.1 on 2023-06-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='country',
            new_name='namelastname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='username',
        ),
    ]
