# Generated by Django 4.2.1 on 2023-06-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_namelastname_users_name_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='name_lastname',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
