# Generated by Django 4.2.1 on 2023-06-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_users_address_users_national_code_users_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('category_id', models.CharField(max_length=255)),
            ],
        ),
    ]
