# Generated by Django 4.2.1 on 2023-06-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_category_categorys_products_orders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='oredr_id',
            new_name='oredr',
        ),
        migrations.RenameField(
            model_name='orderdetails',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
    ]
