# Generated by Django 4.2.1 on 2023-06-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_user_id_carts_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='product_id',
            new_name='product',
        ),
    ]
