# Generated by Django 4.2.1 on 2023-06-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_product_id_carts_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maneger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='N/A', max_length=255)),
                ('username', models.CharField(default='N/A', max_length=255)),
                ('password', models.CharField(default='N/A', max_length=255)),
            ],
        ),
    ]
