# Generated by Django 4.2.1 on 2023-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_maneger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maneger',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maneger',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='maneger',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
