# Generated by Django 4.2 on 2023-06-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_users_address_alter_users_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='national_code',
            field=models.IntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(max_length=255),
        ),
    ]
