# Generated by Django 4.2 on 2023-06-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_users_national_code_alter_users_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(max_length=255),
        ),
    ]
