# Generated by Django 4.2 on 2023-06-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_category_products_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category_id',
            new_name='category',
        ),
    ]
