# Generated by Django 4.2 on 2023-06-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_category_products_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='product',
            new_name='productId',
        ),
        migrations.RenameField(
            model_name='carts',
            old_name='user',
            new_name='userId',
        ),
    ]
