# Generated by Django 4.2 on 2023-06-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_productid_carts_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='user_id',
        ),
    ]
