# Generated by Django 4.2 on 2023-06-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_users_national_code_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(max_length=255),
        ),
    ]
